<p>当单元测试中的测试代码抛出异常时，测试本身就会失败。 因此，无需用<code> try </code>  -  <code> catch </code>结构来包围测试代码以检测故障。 相反，您只需将异常类型移动到方法签名即可。 </p>
<p>当<code> catch </code>块中存在失败断言时，此规则会引发问题。</p>
<h2>不符合规范的代码示例</h2>
<pre>
@Test
public void testMethod() {
  try {
            //一些代码
  } catch (MyException e) {
    Assert.fail(e.getMessage());  //不符合规范的
  }
}
</pre>
<h2>合规的解决方案</h2>
<pre>
@Test
public void testMethod() throws MyException {
    //一些代码
}
</pre>

